import type { BossMechanic } from './types'

export const ENEMY_MECHANICS: Record<string, BossMechanic> = {
  // ── Regular enemies ───────────────────────────────────────────────────────
  goblin:           { chargeMax: 0, chargeName: '毒刃騷擾',  special: 'goblin_poison' },
  orc:              { chargeMax: 3, chargeName: '蓄力重擊',  special: 'orc_rage' },
  skeleton:         { chargeMax: 0, chargeName: '不死之身',  special: 'skeleton_revive' },
  slimeking:        { chargeMax: 0, chargeName: '黏液再生',  special: 'slime_regen' },
  mimic:            { chargeMax: 0, chargeName: '奪命寶藏',  special: 'mimic_treasure' },
  ice_witch:        { chargeMax: 0, chargeName: '骰子封印',  special: 'witch_lock_die' },
  lightning_lancer: { chargeMax: 0, chargeName: '落雷追蹤',  special: 'lancer_thunder' },
  ice_wolf:         { chargeMax: 0, chargeName: '霜咬',      special: 'wolf_frost' },
  yeti:             { chargeMax: 0, chargeName: '冰震衝擊',  special: 'yeti_shield_break' },
  fire_hound:       { chargeMax: 0, chargeName: '嗜血燃焰',  special: 'hound_enrage' },
  bat_dragon:       { chargeMax: 0, chargeName: '俯衝追擊',  special: 'bat_reroll_counter' },
  dark_sorceress:   { chargeMax: 0, chargeName: '惑心詛咒',  special: 'sorceress_curse' },
  // ── Bosses ────────────────────────────────────────────────────────────────
  dragon:      { chargeMax: 0, chargeName: '龍息亂流', special: 'dragon_scramble' },
  dark_knight: { chargeMax: 0, chargeName: '暗黑反擊', special: 'dark_knight_counter' },
  golem:       { chargeMax: 0, chargeName: '石甲護身', special: 'golem_armor', armorTurns: 3 },

  // ── 星蝕裂隙 ──────────────────────────────────────────────────────────────
  rift_imp:        { chargeMax: 0, chargeName: '裂隙干擾',  special: 'rift_imp_chaos' },
  star_sand_golem: { chargeMax: 0, chargeName: '星砂硬殼',  special: 'star_sand_shield' },
  mirror_thief:    { chargeMax: 0, chargeName: '模仿骰型',  special: 'mirror_thief_copy' },
  eclipse_nun:     { chargeMax: 0, chargeName: '暗月禱告',  special: 'eclipse_nun_regen' },
  rift_guardian:   { chargeMax: 0, chargeName: '禁忌反擊',  special: 'rift_guardian_counter' },
  star_reaper:     { chargeMax: 0, chargeName: '收割倒數',  special: 'star_reaper_countdown' },
  eclipse_bishop:  { chargeMax: 0, chargeName: '星蝕審判',  special: 'eclipse_bishop' },

  // ── 裂隙前兆篇 ────────────────────────────────────────────────────────────
  dark_devotee:    { chargeMax: 0, chargeName: '禁忌回復',  special: 'dark_devotee_regen' },
  rift_praying:    { chargeMax: 0, chargeName: '祈禱護盾',  special: 'rift_praying_shield' },
  black_judge:     { chargeMax: 0, chargeName: '裁決之眼',  special: 'black_judge_eye' },
  dark_shaman:     { chargeMax: 0, chargeName: '雙骰審判',  special: 'dark_shaman_dual' },
  bishop_vanguard: { chargeMax: 0, chargeName: '星蝕序章',  special: 'bishop_vanguard_mech' },

  // ── 深海遺城篇 ────────────────────────────────────────────────────────────
  coral_crab:           { chargeMax: 0, chargeName: '共生護殼',  special: 'coral_crab_shell' },
  blue_jellyfish:       { chargeMax: 0, chargeName: '幽光干擾',  special: 'jellyfish_disrupt' },
  tide_piranha:         { chargeMax: 0, chargeName: '迅猛撕咬',  special: 'piranha_frenzy' },
  coral_colossus:       { chargeMax: 0, chargeName: '珊瑚護盾',  special: 'coral_colossus_shield' },
  abyss_anglerfish:     { chargeMax: 0, chargeName: '深淵誘光',  special: 'anglerfish_lure' },
  drowned_guard:        { chargeMax: 0, chargeName: '殞落突擊',  special: 'drowned_guard_charge' },
  deep_lancer:          { chargeMax: 0, chargeName: '退潮長刺',  special: 'deep_lancer_ebb' },
  heavy_drowned:        { chargeMax: 0, chargeName: '深壓甲盾',  special: 'heavy_drowned_pressure' },
  sea_priestess:        { chargeMax: 0, chargeName: '溺亡詛咒',  special: 'sea_priestess_drain' },
  sea_emperor_guard:    { chargeMax: 0, chargeName: '潮汐審判',  special: 'sea_emperor_guard_tide' },
  abyss_siren:          { chargeMax: 0, chargeName: '海妖之歌',  special: 'abyss_siren_song' },
  ancient_shell_knight: { chargeMax: 0, chargeName: '殼甲反彈',  special: 'shell_knight_counter' },
  leviathan_pup:        { chargeMax: 0, chargeName: '深淵衝撞',  special: 'leviathan_charge' },
  sea_queen:            { chargeMax: 0, chargeName: '海皇賜福',  special: 'sea_queen_blessing' },
  sleeping_emperor:     { chargeMax: 0, chargeName: '沉眠甦醒',  special: 'sleeping_emperor_phase' },

  // ── 燃燒王座 ──────────────────────────────────────────────────────────────
  flame_imp:          { chargeMax: 0, chargeName: '添柴',     special: 'flame_imp_ignite' },
  molten_guard:       { chargeMax: 0, chargeName: '熔甲',     special: 'molten_guard_shield' },
  ash_mage:           { chargeMax: 0, chargeName: '灰燼詛咒', special: 'ash_mage_curse' },
  inferno_hound:      { chargeMax: 0, chargeName: '聞火追獵', special: 'inferno_hound_chase' },
  black_flame_knight: { chargeMax: 0, chargeName: '黑焰反擊', special: 'black_flame_counter' },
  fallen_fire_priest: { chargeMax: 0, chargeName: '火祭儀式', special: 'fallen_fire_ritual' },
  throne_demon_king:  { chargeMax: 0, chargeName: '王座餘火', special: 'throne_demon_king' },

  // ── 灰燼王國篇・第二章 ────────────────────────────────────────────────────
  ash_soldier:       { chargeMax: 0, chargeName: '餘火傷口',   special: 'ash_soldier_ember' },
  charred_archer:    { chargeMax: 0, chargeName: '穿煙狙擊',   special: 'charred_archer_snipe' },
  molten_shieldman:  { chargeMax: 0, chargeName: '熔甲反燙',   special: 'molten_guardian_thorns' },
  ember_commander:   { chargeMax: 0, chargeName: '焚旗號令',   special: 'ember_commander_buff' },
  levok:             { chargeMax: 3, chargeName: '灰燼城盾',   special: 'levok_shield_boss' },
  castle_remnant:    { chargeMax: 0, chargeName: '守護記憶',   special: 'castle_soldier_stubborn' },
  ash_guard:         { chargeMax: 0, chargeName: '王宮護衛',   special: 'ash_guard_protect' },
  broken_knight:     { chargeMax: 0, chargeName: '背誓突刺',   special: 'broken_knight_bleed' },
  lost_court_mage:   { chargeMax: 0, chargeName: '記憶錯位',   special: 'soul_mage_dice' },
  laon:              { chargeMax: 4, chargeName: '最後守令',   special: 'laon_memory_boss' },
  tomb_keeper:       { chargeMax: 0, chargeName: '封墓灰塵',   special: 'tomb_keeper_seal' },
  soul_knight:       { chargeMax: 0, chargeName: '鎖魂斬',     special: 'soul_knight_lock' },
  royal_soul:        { chargeMax: 0, chargeName: '王血繼承',   special: 'royal_soul_empower' },
  forbidden_priest:  { chargeMax: 0, chargeName: '六芒反噬',   special: 'forbidden_priest_six' },
  elysia:            { chargeMax: 5, chargeName: '王血反轉',   special: 'elysia_curse_boss' },

  // ── 黑潮王座 ──────────────────────────────────────────────────────────────
  tidal_shell_guard:    { chargeMax: 0, chargeName: '漲潮守勢',  special: 'tidal_shell_guard' },
  azure_jellyfish_envoy:{ chargeMax: 0, chargeName: '幽藍迷光',  special: 'azure_jellyfish_envoy' },
  drowned_court_soldier:{ chargeMax: 0, chargeName: '溺水詛咒',  special: 'drowned_court_soldier' },
  coral_guard_captain:  { chargeMax: 0, chargeName: '珊瑚巨盾',  special: 'coral_guard_captain' },
  deep_pressure_eel:    { chargeMax: 0, chargeName: '深壓電擊',  special: 'deep_pressure_eel' },
  sunken_crown_witch:   { chargeMax: 0, chargeName: '破冠回響',  special: 'sunken_crown_witch' },
  tide_king_ausrein:    { chargeMax: 0, chargeName: '沉睡王威',  special: 'tide_king_ausrein' },
}

export function getEnemyMechanic(enemyId: string): BossMechanic | null {
  return ENEMY_MECHANICS[enemyId] ?? null
}

export const MECHANIC_DESC: Record<string, string> = {
  goblin_poison:      '每次攻擊對你施加 2 層中毒，每回合扣血（不致命）',
  orc_rage:           '每 3 回合蓄力重擊，攻擊傷害翻倍',
  skeleton_revive:    '首次被擊倒時死而復生，回復 30% HP',
  slime_regen:        '每回合開始回復 12 HP',
  mimic_treasure:     '擊敗後額外獲得 30 金幣，但攻擊兇猛',
  witch_lock_die:     '每回合封印隨機一顆骰子，被封印的骰子無法重骰',
  lancer_thunder:       '玩家本回合重骰超過 2 次，追加雷擊傷害',
  wolf_frost:           '每次攻擊施加 1 層霜凍（最多 2 層），每層使你的重骰上限 -1；每回合消退 1 層',
  yeti_shield_break:    '每 3 回合進行冰震衝擊，完全無視護盾直接傷害 HP（攻擊前會預警）',
  hound_enrage:         '每次成功傷害後攻擊力永久 +8%（最多 3 層）',
  bat_reroll_counter:   '你每次重骰，本回合敵人追加攻擊力 ×15% 額外傷害',
  sorceress_curse:      '每次攻擊後 40% 機率詛咒你，下次出手傷害 -30%',
  dragon_scramble:    '每次擲骰後，隨機一顆骰子被龍息打亂',
  dark_knight_counter:'你每次造成的傷害，25% 反彈回自身',
  golem_armor:        '前 3 回合石甲護身，完全免疫傷害',
  // 星蝕裂隙
  rift_imp_chaos:          '每回合開始，禁忌點數有 30% 機率改變',
  star_sand_shield:        '出手含禁忌點數時，魔偶額外獲得護盾（1顆+10、2顆+18、3顆以上+30）',
  mirror_thief_copy:       '玩家打出三條以上時，下次攻擊傷害 +40%',
  eclipse_nun_regen:       '每 2 回合回復 25 HP；玩家含禁忌點數出手時額外再回復 15 HP',
  rift_guardian_counter:   '玩家出手含禁忌點數時反擊（1顆8傷、2顆16傷、3顆以上25傷+1層易傷）',
  star_reaper_countdown:   '每 4 回合發動大攻擊；玩家打出不含禁忌的三條以上可延後 1 回合',
  eclipse_bishop:          '每 2 回合宣告新禁忌點數（第一階段）→ 第二階段雙重禁忌 → 第三階段每 3 回合星蝕審判',
  // 裂隙前兆篇
  dark_devotee_regen:   '每 2 回合指定禁忌點數；你踩到 → 牠回復 10 HP',
  rift_praying_shield:  '每 2 回合指定禁忌點數；你踩到 → 牠獲得 8 護盾',
  black_judge_eye:      '每 2 回合指定禁忌點數；你避開 → 牠陷入易傷 2 回；你踩到 → 牠憤怒強化',
  dark_shaman_dual:     '每 2 回合指定禁忌＋祝福點數；踩禁忌 → 自傷 10 HP；含祝福 → 自獲 8 護盾',
  bishop_vanguard_mech: '每 2 回合指定禁忌/祝福點數；HP < 60% 進入第二階段（雙骰）；HP < 20% 裂隙門開啟，3 回合後強化爆發',
  // 深海遺城篇
  coral_crab_shell:       'HP 降至 50% 以下時，每回合獲得 15 護盾；玩家打出三條以上可破除',
  jellyfish_disrupt:      '每 2 回合隨機改變一顆骰子；幽光使玩家下回合重骰 -1（最多 2 回合）',
  piranha_frenzy:         '每次玩家氧氣降低時追加小攻擊；血量低於 40% 時攻擊 +25%',
  coral_colossus_shield:  '高防禦；每 3 回合獲得 20 護盾；打出葫蘆以上可破除護盾並使其陷入易傷',
  anglerfish_lure:        '每次玩家重骰，深淵鮟鱇下次攻擊 +15%（最多蓄積至 +60%）；氧氣每回合額外扣 1',
  drowned_guard_charge:   '每 3 回合蓄力重擊，傷害翻倍；第一次倒地後復生，回復 20% HP',
  deep_lancer_ebb:        '退潮時攻擊 +30%；每 2 回合變更攻擊目標，使玩家護盾減半',
  heavy_drowned_pressure: '深壓時防禦 +8，且受到傷害 -20%；每 4 回合發動水壓衝擊',
  sea_priestess_drain:    '每 2 回合扣除玩家 1 點氧氣；HP < 40% 時，每回合詛咒玩家（下次攻擊傷害 -20%）',
  sea_emperor_guard_tide:  '每 2 回合切換潮汐；漲潮時獲得 15 護盾；退潮時攻擊 +20%；HP < 50% 後潮汐反制',
  abyss_siren_song:       '每 2 回合改變一顆骰子並扣 1 氧氣；歌聲迷惑使玩家下次攻擊 -15%',
  shell_knight_counter:   '受到超過 60 傷害時反擊（傷害的 30%）；每 3 回合護殼蛻生，恢復 25 HP',
  leviathan_charge:       '每 3 回合蓄力深淵衝撞，造成 ×2 傷害；HP < 30% 後攻擊每回合 +10%（最多 +40%）',
  sea_queen_blessing:     '氧氣歸零時立即回復 40 HP；每 2 回合指定詛咒點數，玩家踩到時受額外傷害',
  sleeping_emperor_phase: '第一階段：潮汐每 2 回合切換；第二階段（HP<60%）：施加深壓+退潮複合效果；第三階段（HP<30%）：潮汐每回合切換，發動龍王波',
  // 燃燒王座
  flame_imp_ignite:     '每次玩家魔焰值增加時，下次攻擊 +10%',
  molten_guard_shield:  '魔焰值 3 以上時獲得護盾；魔焰值 5 以上時護盾量加倍',
  ash_mage_curse:       '每 3 回合施加灰燼詛咒：玩家下一次回復效果降低 50%；魔焰值 5 以上時改為完全無法回復 1 回合',
  inferno_hound_chase:  '魔焰值越高，攻擊越強；魔焰值 3 以上攻擊 +15%；魔焰值 5 以上追加小攻擊；魔焰反噬後立即追擊',
  black_flame_counter:  '玩家單回合造成超過 90 傷害時反擊；魔焰值 4 以上時受到傷害 -20%（打出小順子以上可破除 1 回合）',
  fallen_fire_ritual:   '每 4 回合發動火祭儀式；魔焰值 4 以上時對玩家造成大量火焰傷害並給予護盾；玩家打出兩對以上可延後 1 回合',
  throne_demon_king:    '第一階段每回合魔焰 +1；第二階段玩家高傷觸發燃魂契約；第三階段每回合獲得崩壞層（最多 5 層），指定骰型可移除崩壞',
  // 灰燼王國篇・第二章
  ash_soldier_ember:        '餘燼 2+ 層時攻擊 40% 機率附加 2 層燃燒；死亡時給敵方隨機隊友 8 護盾',
  charred_archer_snipe:     '專攻生命最低的角色；餘燼 3+ 層時暴擊率提升，傷害 +20%',
  molten_guardian_thorns:   '每次攻擊獲得 8 護盾；受到近戰傷害時 30% 機率對攻擊者附加 2 層燃燒',
  ember_commander_buff:      '每 2 回合為全體敵人提升攻擊（+15%，持續 1 回合）；餘燼 3+ 層時強化全體敵人燃燒傷害',
  levok_shield_boss:        '每 3 回合累積灰燼城盾（+20 護盾）；有護盾時受傷 -20%；盾被打破後下回合重置骰子；餘燼 4 層時清除負面狀態並攻擊提升',
  castle_soldier_stubborn:  '首次倒地時以 1 HP 存活；王城記憶「加冕之日」期間護盾效果 +50%',
  ash_guard_protect:        '為血量最低的友方承受部分傷害；自身低血量時獲得 12 護盾；「王城陷落」時護衛削弱但攻擊提升',
  broken_knight_bleed:      '攻擊時附加 2 層中毒（流血替代）；對有負面狀態的目標追加 15 傷害；「背叛之刻」必打最低血量目標',
  soul_mage_dice:            '每 2 回合隨機將 1 顆骰子 -1 點；「戰火之夜」時技能額外附加 2 層燃燒',
  laon_memory_boss:         '根據王城記憶切換被動：加冕→每回合護盾+12；戰火→攻擊附加燃燒；背叛→攻擊附加易傷；陷落→傷害+25%但防禦-3；小怪全滅後進入孤軍狀態，攻擊+20%',
  tomb_keeper_seal:         '每 3 回合施加封墓標記：下一次治療效果降低 50%；玩家觸發王血反噬時回復 20 HP',
  soul_knight_lock:         '攻擊時附加 +1 層王血詛咒；每 3 回合封鎖 1 顆骰子本回合不能重骰；低血量時獲得 15 護盾',
  royal_soul_empower:        '死亡時給所有其他敵人 +12 攻擊力（1 回合）和 10 護盾；玩家出 6 點骰時有 30% 機率附加 1 層王血詛咒',
  forbidden_priest_six:      '玩家王血詛咒 5 層時回復敵方全體 30 HP；玩家出 6 點骰時 30% 機率反擊 10 傷害',
  elysia_curse_boss:        '詛咒 3+ 層時傷害 +20%；玩家觸發反噬→艾莉西亞獲得 20 護盾；每 5 回合施放「王血反轉」（詛咒層數×8 全體傷害）；HP<50% 後縮短至每 3 回合；HP<20% 停止召喚',
  // 黑潮王座
  tidal_shell_guard:    '漲潮時受傷 -20% 並獲得減傷；有護盾時受攻擊反彈 5 傷害',
  azure_jellyfish_envoy:'每 2 回合鎖定玩家 1 顆骰子本回合不能重骰；亂流狀態下額外改變 1 顆骰子',
  drowned_court_soldier:'攻擊時消耗玩家 1 點氧氣；死亡後產生怨念水泡，下回合爆炸造成 15 傷害',
  coral_guard_captain:  '每 3 回合獲得 25 護盾；低傷害（<20）被免疫；葫蘆以上破防並施加易傷',
  deep_pressure_eel:    '深壓狀態下速度與攻擊提升；低骰（1-3）增傷；每 2 回合壓流電擊，全體小傷+重骰-1',
  sunken_crown_witch:   '每 2 回合強制切換潮汐；每次潮汐切換累積法力（3 層後下次技能全體攻擊）',
  tide_king_ausrein:    '三條血條：王座甦醒（鎖骰+護盾）→ 深壓審判（召喚+亂流）→ 沉海王權（高傷+氧氣上限-1）',
}
